In [1]:
!pip list

Package                                  Version
---------------------------------------- -------------------
absl-py                                  1.4.0
accelerate                               1.13.0
access                                   1.1.10.post3
affine                                   2.4.0
aiofiles                                 24.1.0
aiohappyeyeballs                         2.6.1
aiohttp                                  3.13.5
aiosignal                                1.4.0
aiosqlite                                0.22.1
alabaster                                1.0.0
albucore                                 0.0.24
albumentations                           2.0.8
ale-py                                   0.11.2
alembic                                  1.18.4
altair                                   5.5.0
annotated-doc                            0.0.4
annotated-types                          0.7.0
antlr4-python3-runtime                   4.9.3
anyio                         

In [3]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3],[4,5,6]])

print(arr1)
print(arr2)
print()
print(arr1.shape) # 1차원 (5,)
print(arr2.shape) # 2차원 (2,3)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]

(5,)
(2, 3)


In [5]:
# 난수 이용한 2차원 배열
# randn : random normal distribution (정규분호)
# 정규분포인가? normal, 정규, 가우시안
np.random.randn(3)

array([0.05626298, 0.11812923, 1.15266813])

In [7]:
arr3 = np.random.randn(3)
arr4 = np.random.randn(2,3)

print(arr3)
print()
print(arr4)

[ 1.97526549  0.34851596 -1.22666684]

[[ 0.33868011  0.08572174  1.52330726]
 [-0.46773784  0.4108298  -0.37049951]]


In [10]:
# 원소를 0 또는 1로 초기화

arr5 = np.zeros(5)
arr6 = np.ones((2,3))

print(arr5)
print()
print(arr6)

[0. 0. 0. 0. 0.]

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# arange() 와 reshape() (***)
# arange() : array + range
# arange(start, end, step)

arr7 = np.arange(20, 200, 10)

print(arr7)
print(arr7.shape)
print(len(arr7))

[ 20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180 190]
(18,)
18


In [17]:
# 반드시 알아야 해요 (변환)
arr7.reshape(3, -1)

array([[ 20,  30,  40,  50,  60,  70],
       [ 80,  90, 100, 110, 120, 130],
       [140, 150, 160, 170, 180, 190]])

In [18]:
arr8 = arr7.reshape(3, -1)
arr8

array([[ 20,  30,  40,  50,  60,  70],
       [ 80,  90, 100, 110, 120, 130],
       [140, 150, 160, 170, 180, 190]])

In [20]:
# 배열 다루기
ar1 = np.arange(1, 21, 1)
print(ar1[1])

2


In [21]:
len(ar1)

20

In [23]:
ar2 = ar1.reshape(2, -1)
ar2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [24]:
ar2[1]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [25]:
ar2[1][1]

np.int64(12)

In [26]:
ar2[1][4]

np.int64(15)

In [27]:
ar2[1][1] = 100
print(ar2[1][1])

100


In [28]:
ar2

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11, 100,  13,  14,  15,  16,  17,  18,  19,  20]])

In [31]:
print(ar2[0])
print(ar2[1])
print(ar2[0][-1])

[ 1  2  3  4  5  6  7  8  9 10]
[ 11 100  13  14  15  16  17  18  19  20]
10


In [32]:
# 배열의 산술연산 : 배열의 연산은 배열 원소에 각각 적용된다

ar1 = np.arange(1, 11, 1)
ar2 = ar1 + 3 # broadcasting(각 원소에 적용)
ar3 = ar2 * 3


print(ar1)
print()
print(ar2)
print()
print(ar3)
print()

[ 1  2  3  4  5  6  7  8  9 10]

[ 4  5  6  7  8  9 10 11 12 13]

[12 15 18 21 24 27 30 33 36 39]



In [41]:
# 배열의 통계 메소드 사용
arr = np.array([[5,7,9], [-7, -6, 19], [6,9,11]])

print(arr)
print(arr.sum()) # 전체 요소의 합
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.argmax())

[[ 5  7  9]
 [-7 -6 19]
 [ 6  9 11]]
53
5.888888888888889
19
-7
5


In [43]:
arr.max(axis=0)

array([ 6,  9, 19])

In [44]:
arr.max(axis=1)

array([ 9, 19, 11])

In [45]:
# 조건식 사용한 연산
arr

array([[ 5,  7,  9],
       [-7, -6, 19],
       [ 6,  9, 11]])

In [46]:
arr>0

array([[ True,  True,  True],
       [False, False,  True],
       [ True,  True,  True]])

In [47]:
condition = (arr > 0)

In [48]:
condition.sum()

np.int64(7)

In [49]:
# np.where

# arr < 0 조건식
# 조건식이 참(True) (arr < 0) >>> 0 반환, 아니면 arr 출력

np.where(arr<0, 0, arr)

array([[ 5,  7,  9],
       [ 0,  0, 19],
       [ 6,  9, 11]])

In [50]:
arr

array([[ 5,  7,  9],
       [-7, -6, 19],
       [ 6,  9, 11]])

In [51]:
arr.sort(0)
# axis=0 열단위로 원소를 정렬

In [52]:
arr

array([[-7, -6,  9],
       [ 5,  7, 11],
       [ 6,  9, 19]])

In [53]:
arr.sort(1)
# axis=1 행단위 원소를 정렬

In [54]:
arr

array([[-7, -6,  9],
       [ 5,  7, 11],
       [ 6,  9, 19]])

In [55]:
# np.sort(), arr.sort() 차이 : 원본 수정 여부

import numpy as np

arr10 = np.array([3,1,4,5,2,1,5,3,4])
print(arr10) # 원본

[3 1 4 5 2 1 5 3 4]


In [56]:
np.sort(arr10) # 원본 변경 없음 (default: 오름차순)

array([1, 1, 2, 3, 3, 4, 4, 5, 5])

In [57]:
arr10

array([3, 1, 4, 5, 2, 1, 5, 3, 4])

In [58]:
arr10.sort() # 원본 변경됨 (default: 오름차순)
arr10

array([1, 1, 2, 3, 3, 4, 4, 5, 5])

In [60]:
# argsort() : 정렬된 인덱스
arr11 = np.array([30, 10, 40, 20])
print(arr11)

[30 10 40 20]


In [61]:
np.argsort(arr11)

array([1, 3, 0, 2])

In [62]:
# eos